services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - users-data:/data
      
  frontend:
    depends_on: [backend]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - API_PROXY_TARGET=http://backend:8000
      - WATCH_USE_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  users-data:
